module.exports=(shipping,knex,jwt)=>{
    shipping.get('/regions',(req,res)=>{
        knex('shipping_region').select('*')
        .then((data)=>{res.send(data)})
        .catch((err)=>{res.send(err)})
    })
    shipping.get('/regions/:regions_id',(req,res)=>{
        knex('shipping').select('*').where('shipping_region_id',req.params.regions_id)
        .then((data)=>{res.send(data)})
        .catch((err)=>{res.send(err)})
    })
}